branches:
  except:
    - /^issue\d+/
    - /^gh\d+/
language: perl
notifications:
  slack:
    rooms:
      - cpanelllc:V6BAp4TZMPzu6ieWNznycYKK#busy-camels
env:
  global:
    - PERL_USE_UNSAFE_INC=0
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=1
perl:
  - "5.14"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.12"
  - "5.10"
  - "blead"
matrix:
  include:
    - perl: 5.28
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
script:
  - perl Makefile.PL && make test
